// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     OrderEvent.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayItem(r []Item, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeItem(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayItemWrapper struct {
	Target *[]Item
}

func (_ ArrayItemWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayItemWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayItemWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayItemWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayItemWrapper) Finalize()                        {}
func (_ ArrayItemWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayItemWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]Item, 0, s)
	}
}
func (r ArrayItemWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayItemWrapper) AppendArray() types.Field {
	var v Item
	v = NewItem()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
