// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     OrderEvent.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OrderEvent struct {
	OrderId string `json:"orderId"`

	Timestamp int64 `json:"timestamp"`

	Items []Item `json:"items"`
}

const OrderEventAvroCRC64Fingerprint = "l\tşվ\"\xc7"

func NewOrderEvent() OrderEvent {
	r := OrderEvent{}
	r.Items = make([]Item, 0)

	return r
}

func DeserializeOrderEvent(r io.Reader) (OrderEvent, error) {
	t := NewOrderEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOrderEventFromSchema(r io.Reader, schema string) (OrderEvent, error) {
	t := NewOrderEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOrderEvent(r OrderEvent, w io.Writer) error {
	var err error
	err = vm.WriteString(r.OrderId, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	err = writeArrayItem(r.Items, w)
	if err != nil {
		return err
	}
	return err
}

func (r OrderEvent) Serialize(w io.Writer) error {
	return writeOrderEvent(r, w)
}

func (r OrderEvent) Schema() string {
	return "{\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"items\",\"type\":{\"items\":{\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}],\"name\":\"Item\",\"type\":\"record\"},\"type\":\"array\"}}],\"name\":\"com.example.alerting.models.OrderEvent\",\"type\":\"record\"}"
}

func (r OrderEvent) SchemaName() string {
	return "com.example.alerting.models.OrderEvent"
}

func (_ OrderEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OrderEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OrderEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OrderEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OrderEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OrderEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OrderEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ OrderEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OrderEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.OrderId}

		return w

	case 1:
		w := types.Long{Target: &r.Timestamp}

		return w

	case 2:
		r.Items = make([]Item, 0)

		w := ArrayItemWrapper{Target: &r.Items}

		return w

	}
	panic("Unknown field index")
}

func (r *OrderEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *OrderEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ OrderEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OrderEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OrderEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ OrderEvent) Finalize()                        {}

func (_ OrderEvent) AvroCRC64Fingerprint() []byte {
	return []byte(OrderEventAvroCRC64Fingerprint)
}

func (r OrderEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["orderId"], err = json.Marshal(r.OrderId)
	if err != nil {
		return nil, err
	}
	output["timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	output["items"], err = json.Marshal(r.Items)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OrderEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["orderId"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.OrderId); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for orderId")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timestamp")
	}
	val = func() json.RawMessage {
		if v, ok := fields["items"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Items); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for items")
	}
	return nil
}
